### ISSUE TITLE
Attribute/StyleAttribute internal initializers

### ISSUE THREAD

**Issue by foscomputerservices** [dokun1/Vaux#22]
In looking the definitions for Attribute and StyleAttribute, is there a reason that public initializers are not provided?  I suspect that they were just inadvertently omitted (I do it *all* the time; one of the less intuitive *features* of swift IMO).

```swift
public struct Attribute {
  public let key: String
  public let value: String?
}

public struct StyleAttribute {
  public let key: String
  public let value: String
}
```

**Comment by mbarnach** [comment]
Good catch! I'm making a PR to fix those. 👍

**Comment by dokun1** [comment]
Thanks for finding this @foscomputerservices! Bad miss on my part - thanks again to @mbarnach for the fix 🎉
